# Makefile for generating websites from Agda sources

##############################################################################
# PARAMETERS
#
# Name   Purpose
# ---------------------------
# DIR    import include-path
# ROOT   root module file
# HTML   generated HTML files
# MD     generated MD files
# TEMP   temporary files

# DEFAULTS

DIR   := doc
ROOT  := doc/README.agda
HTML  := docs/html
MD    := docs/md
TEMP  := /tmp/html

##############################################################################
# VARIABLES

SHELL=/bin/sh

# Characters:

EMPTY :=

SPACE := $(EMPTY) $(EMPTY)

# A single newline:
define NEWLINE :=


endef

# Shell commands for calling Agda:
AGDA-Q := agda --include-path=$(DIR) --trace-imports=0
AGDA-V := agda --include-path=$(DIR)

# Name of ROOT module:
NAME := $(subst /,.,$(subst $(DIR)/,,$(basename $(ROOT))))

# Target files:
HTML-FILES := $(sort \
	$(HTML)/$(NAME).html \
	$(patsubst $(TEMP)/%,$(HTML)/%,$(shell \
		rm -f $(TEMP)/*.html; \
		$(AGDA-Q) --html --html-dir=$(TEMP) $(ROOT); \
		ls $(TEMP)/*.html)))

# Names of modules imported (perhaps indirectly) by ROOT:
IMPORT-NAMES := $(subst $(HTML)/,,$(basename $(HTML-FILES)))

# Paths of modules imported (perhaps indirectly) by ROOT:
IMPORT-PATHS := $(subst .,/,$(IMPORT-NAMES))

# Names of modules in DIR:
MODULE-NAMES := $(sort $(subst /,.,$(subst $(DIR)/,,$(basename $(shell \
		find $(DIR) -name '*.agda')))))

# Names of imported modules in DIR:
AGDA-NAMES := $(filter $(MODULE-NAMES),$(IMPORT-NAMES))

# Paths of imported modules in DIR:
AGDA-PATHS := $(subst .,/,$(AGDA-NAMES))

# Agda source files:
AGDA-FILES := $(addprefix $(DIR)/,$(addsuffix .agda,$(AGDA-PATHS)))

# Target files:
MD-FILES := $(addprefix $(MD)/,$(addsuffix /index.md,$(IMPORT-PATHS)))

##############################################################################
# RULES

.PHONY: help
export HELP
help:
	@echo "$$HELP"

.PHONY: debug
export DEBUG
debug:
	@echo "$$DEBUG"

# Clean and regenerate the website:

# Note: Generating a website for the Agda standard library may take about 2 mins

.PHONY: website
website:
	@echo Generating a website for the Agda standard library may take about 2 mins
	@echo Clean ...
	@$(MAKE) -f Makefile clean-all
	@echo Generate HTML in $(HTML) ...
	@$(MAKE) -f Makefile html
	@echo Generate Markdown in $(MD) ...
	@$(MAKE) -f Makefile md
	@echo ... finished
	@echo
	@echo To preview the generated webite:
	@echo "    make serve"
	@echo

# Check Agda source files:

.PHONY: check
check:
	@$(AGDA-V) $(ROOT)

# Generate HTML web pages:

.PHONY: html
html: $(AGDA-FILES)
	@mkdir -p $(HTML) && cp $(TEMP)/* $(HTML)

# Generate Markdown sources for web pages:

# `agda --html --html-highlight=code ROOT.lagda` produces highlighted HTML files
# from plain `agda` and literate `lagda` source files. However, the extension is
# `tex` for HTML produced from `lagda` files. It is `html` for `agda` files, but
# needs to be wrapped in `<pre class="Agda">...</pre>` tags.

# The links in the files assume they are all in the same directory, and that the
# files have extension `.html`. Adjusting them to hierarchical links with
# directory URLs involves replacing the dots in the basenames of the files by
# slashes, prefixing the href by the relative path to the top of the hierarchy,
# and appending a slash to the file path. All URLs that start with A-Z or a-z
# are assumed to be links to modules, and adjusted (also in the prose of
# literate Agda source files).

# The links generated by Agda always start with the file name. This could be
# omitted for local links where the id is in the same file. Similarly, the
# links to modules in the same directory could be optimized.

.PHONY: md
md: $(MD-FILES)

# Create HTML files in $(MD):
$(MD):
	@$(AGDA-Q) --html --html-highlight=code --html-dir=$(MD) $(ROOT)

# Use an order-only prerequisite:
$(MD-FILES): $(MD)/%/index.md: $(AGDA-FILES) | $(MD)
	@mkdir -p $(@D)
# Wrap *.html files in <pre> tags, and rename *.html and *.tex files to *.md:
	@if [ -f $(MD)/$(subst /,.,$*).html ]; then \
	    mv -f $(MD)/$(subst /,.,$*).html $@; sd '\A' '<pre class="Agda">' $@; sd '\z' '</pre>' $@; \
	else \
	    mv -f $(MD)/$(subst /,.,$*).tex $@; \
	fi
# Prepend front matter:
	@sd -- '\A' '---\ntitle: $(*F)\nhide: toc\n---\n\n# $(subst /,.,$*)\n\n' $@
# Use directory URLs:
	@sd '(href="[A-Za-z][^"]*)\.html' '$$1/' $@
# Replace `.`-separated filenames in URLs by `/`-separated paths:
	@while grep -q 'href="[A-Z][^".]*\.' $@; do \
	    sd '(href="[A-Za-z][^".]*)\.' '$$1/' $@; \
	done
# Prefix paths by relative path to top level:
	@sd 'href="([A-Za-z])' 'href="$(subst $(SPACE),$(EMPTY),$(foreach d,$(subst /, ,$*),../))$$1' $@

# Serve the generated website for a local preview

.PHONY: serve
serve:
	@mkdocs serve

# Update and build the website, then deploy it on GitHub Pages from the gh-pages branch

.PHONY: deploy
deploy: all
	@mkdocs gh-deploy --force

# Remove all files generated from ROOT

.PHONY: clean-all clean-html clean-md
clean-all: clean-html clean-md

clean-html:
	@rm -rf $(HTML)

clean-md:
	@rm -rf $(MD)

# Texts

define HELP

make -f Makefile = make -f Makefile help
  Display this list of make targets
make -f Makefile website
  Generate website for $(ROOT)
make -f Makefile check
  Check loading the Agda source files for $(ROOT)
make -f Makefile serve
  Serve the generated website locally
make -f Makefile deploy
  Deploy the website on GitHub Pages 
make -f Makefile html
  Generate web page sources in ${HTML}
make -f Makefile md
  Generate web page sources in $(MD)
make -f Makefile clean-all
  Remove all generated files
make -f Makefile clean-md
  Remove generated Markdown files
make -f Makefile clean-html
  Remove generated HTML files
make -f Makefile debug
  Display the values of variables

Note: all make commands load $(ROOT) to initialize HTML-FILES

endef

define DEBUG

DIR:  $(DIR)
ROOT: $(ROOT)
NAME: $(NAME)

IMPORT-NAMES (1-5): $(wordlist 1, 5, $(IMPORT-NAMES))

IMPORT-PATHS (1-5): $(wordlist 1, 5, $(IMPORT-PATHS))

MODULE-NAMES (1-5): $(wordlist 1, 5, $(MODULE-NAMES))

AGDA-NAMES   (1-5): $(wordlist 1, 5, $(AGDA-NAMES))

AGDA-PATHS   (1-5): $(wordlist 1, 5, $(AGDA-PATHS))

AGDA-FILES   (1-5): $(wordlist 1, 5, $(AGDA-FILES))

HTML-FILES   (1-5): $(wordlist 1, 5, $(HTML-FILES))

MD-FILES     (1-5): $(wordlist 1, 5, $(MD-FILES))

endef