nav:
  - About:
    - index.md
    - installation-guide.md
  - README:
    - md/README/index.md
    - md/README/*
  - Library:
    - Library/index.md
    - md/*
  - HTML: html/README.html

preserve_directory_names: true

sort:
  sections: mixed