nav:
  - About:
    - index.md
    - installation-guide.md
  - README:
    - md/README/index.md
    - md/Everything/index.md
    - md/EverythingSafe/index.md
    - md/README/
  - Library:
    - md/index/index.md
    - md/*
  - HTML: html/index.html

preserve_directory_names: true

sort:
  sections: mixed